### ISSUE TITLE
Error with Relative folder path

### ISSUE THREAD

**Issue by brothermechanic** [jayanam/batex#3]
```
Traceback (most recent call last):
  File "/home/bm/.config/blender/2.81/scripts/addons/batex-master/bex_op.py", line 16, in execute
    bat_export.do_export()
  File "/home/bm/.config/blender/2.81/scripts/addons/batex-master/bex_export.py", line 46, in do_export
    path_mode='ABSOLUTE')
  File "/usr/share/blender/2.81/scripts/modules/bpy/ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Error: Traceback (most recent call last):
  File "/usr/share/blender/2.81/scripts/addons/io_scene_fbx/__init__.py", line 617, in execute
    return export_fbx_bin.save(self, context, **keywords)
  File "/usr/share/blender/2.81/scripts/addons/io_scene_fbx/export_fbx_bin.py", line 3194, in save
    ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
  File "/usr/share/blender/2.81/scripts/addons/io_scene_fbx/export_fbx_bin.py", line 3102, in save_single
    encode_bin.write(filepath, root, FBX_VERSION)
  File "/usr/share/blender/2.81/scripts/addons/io_scene_fbx/encode_bin.py", line 291, in write
    with open(fn, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '//export/v15//window-bottom.fbx'

location: /usr/share/blender/2.81/scripts/modules/bpy/ops.py:201



location: <unknown location>:-1


```

With Absolute path it works

**Comment by jayanam** [comment]
Ok, will have a look

**Comment by scrollwing** [comment]
I'm having the exact same error. Any idea with this?

**Comment by jayanam** [comment]
Now I can reproduce for different partition here under Windows OS

**Comment by HamWoe** [comment]
Same error message for me too. Any ideas Jayanam? 
![image](https://user-images.githubusercontent.com/20248517/76211405-10394e80-61fe-11ea-9a72-e7aea709f6c5.png)

**Comment by jayanam** [comment]
Ok thx, is the file you want to export to on a different disk partition?

**Comment by HamWoe** [comment]
Yes, to save to an External hard drive!

**Comment by jayanam** [comment]
@HamWoe Which version of Blender are you using? I tried atm with 2.83 and works for every folder.

**Comment by Cody38** [comment]
I'm on 2.83, and was able to successfully batch export to a folder on my C: drive on my desktop. After changing to export to E: for my game project, I got the same error as above (unknown location.) I tried to reset it to my desktop and that didn't work, now it won't export anywhere at all. I've reinstalled and everything. 

Traceback (most recent call last):
  File "C:\Users\Zack\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\batex-master\bex_op.py", line 16, in execute
    bat_export.do_export()
  File "C:\Users\Zack\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\batex-master\bex_export.py", line 77, in do_export
    bpy.ops.object.mode_set(mode='OBJECT')
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\2.83\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.object.mode_set.poll() failed, context is incorrect

location: <unknown location>:-1

**Comment by tomoprime** [comment]
I also have the same file error in Windows 10 with Blender 2.83.2. I noticed in the Console output below it says: **path_mode='ABSOLUTE'**, but this path is relative no? I had chose a local folder inside my project called _FBX_ which looks like _//FBX_.

To workaround since the plugin needs an Absolute path I went and posted `C:\Users\Tomo\Documents\Deadpool\FBX\ `directly inside my _Export folder:_ path and it exported fine. Note if you use the browse button it will still put //blah/blah even if you select the C:\ drive. 

> Error: Traceback (most recent call last):
>   File "C:\Users\Tomo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\batex\bex_op.py", line 16, in execute
>     bat_export.do_export()
>   File "C:\Users\Tomo\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\batex\bex_export.py", line 102, in do_export
>     path_mode='ABSOLUTE')
>   File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\bpy\ops.py", line 201, in __call__
>     ret = op_call(self.idname_py(), None, kw)
> RuntimeError: Error: Traceback (most recent call last):
>   File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_scene_fbx\__init__.py", line 634, in execute
>     return export_fbx_bin.save(self, context, **keywords)
>   File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3198, in save
>     ret = save_single(operator, context.scene, depsgraph, filepath, **kwargs_mod)
>   File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_scene_fbx\export_fbx_bin.py", line 3106, in save_single
>     encode_bin.write(filepath, root, FBX_VERSION)
>   File "C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\addons\io_scene_fbx\encode_bin.py", line 291, in write
>     with open(fn, 'wb') as f:
> FileNotFoundError: [Errno 2] No such file or directory: '//FBX/Body.fbx'
> 
> location: C:\Program Files\Blender Foundation\Blender 2.83\2.83\scripts\modules\bpy\ops.py:201
> 
> 
> 
> location: <unknown location>:-1

**Comment by jayanam** [comment]
I turn the relative folder now on export into the absolute folder. Please test latest version 0.5.0.0

**Comment by phil123456** [comment]
same problem here with the latest version

I downloaded the master and it is v 6.0

I cloned the repo, and ziped it, installed, yet again, v 0.6
