### ISSUE TITLE
No armatures in exported models

### ISSUE THREAD

**Issue by Optimus97100** [jayanam/batex#6]
I'm using Blender version 2.82.7.
When I batch export a **rigged** character with separated parts and import them back into Blender (first time encountered this when imported them into SteamVR), they lose their armatures completely. Armature, on the other hand, exports as a single separate object.

**Comment by jayanam** [comment]
Alright, will add this option to the export

**Comment by jayanam** [comment]
Now you can define if you want to export armature and animations
