### ISSUE TITLE
Error on export.

### ISSUE THREAD

**Issue by MOAdev** [jayanam/batex#9]
[https://imgur.com/a/Pvef0Rv](url)

I had this before, and just installed latest version (after uninstalling old one).

**Comment by jayanam** [comment]
Please check if you have the object selected before exporting, anyway, I
will fix the bug.

**Comment by MOAdev** [comment]
Thank you! For confirmation that the object is selected, and has a valid export directory selected:
[https://imgur.com/a/3geng01](url)

**Comment by jayanam** [comment]
The export older is a relative folder... could it be that you export to a
different drive? Not C:, perhaps D:...? Can you try to use an
absolute export path?

**Comment by MOAdev** [comment]
Ah! I mistakenly thought by using the folder icon, it would copy the complete path to the chosen folder. Pasting the path in manually removed all errors.

**Comment by jayanam** [comment]
Ok thx, still have to catch the error
